title: "Katia Sarah Demil"
email: katiademil14@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
 I'm Katia, just another human, and physics students who is passionate
 about a lot of things including tech and coding!
baseurl: "/" 
url: "https://katiachan.github.io" 
twitter_username: 
github_username:  katiachan

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg